services:
  - type: web
    name: flask-sarima-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=1 --timeout=120 --log-level=info
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MAX_THREADS
        value: 2
      - key: PYTHONUNBUFFERED
        value: true
